name: Digital_Resume_Backend

on: 
  push:
    branches:
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps: 
    - name: checkout-code
      uses: actions/checkout@v2
    
    - name: authenticate-ssh and deploy
      env: 
        SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
      run: |
        echo "${{ secrets.SSH_SECRET_KEY }}" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-35-154-182-69.ap-south-1.compute.amazonaws.com "sudo bash ~/digital-resume-api/project.sh"

